server:
  port: 8085

logging:
  level:
    "[org.hibernate.sql]": debug
  file:
    path: logs

security:
  jwt:
    secret: ${SPRING_JWT_TOKEN:mZfpLztVGV1ROkxXpXNRwFdoIUuJArRI4k+ouB+Hr4rfydy7hGfMY0+tnXJkmDuMgQkPQ1O6s5VUg5LoepC42g==}
    expiration: ${SPRING_JWT_EXPIRATION:8640000}

spring:
  jackson:
    default-property-inclusion: NON_NULL
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
